fn_single_line = true
imports_granularity = "Crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 110
struct_field_align_threshold = 40
trailing_comma = "Vertical"
wrap_comments = true
unstable_features = true
