# Specify the maximum width of each line
fn_single_line = true
imports_granularity = "Crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 100
struct_field_align_threshold = 30
trailing_comma = "Always"
wrap_comments = true
